### ISSUE TITLE
Hackage release

### ISSUE THREAD

**Issue by emilypi** [sullyj3/buttplug-hs-core#1]
Hi @sullyj3 - do you plan on releasing this to hackage?

**Comment by sullyj3** [comment]
Hey! I was planning to eventually, however it's not really in a state I'm proud of at the moment, and I haven't had the chance to work on it so much lately. I have a couple of things to rework about it, I think. If you've been using it, I'd definitely appreciate feedback or suggestions!

**Comment by emilypi** [comment]
I don't have anything currently that I could use to test the lib, but I'd be happy to find something and contribute data points. If you have anything in particular you'd need code wise, I"m happy to help with that too, as long it's a clear description of the problem (as an issue or smth).

**Comment by sullyj3** [comment]
I appreciate that and I'll keep the offer in mind :)

**Comment by sullyj3** [comment]
[It's up!](https://hackage.haskell.org/package/buttplug-hs-core) 

Just waiting for the docs to build so I can check they're ok, then I'll close this.
